"""Part 4: Deep dives — additional content to reach 45k words target"""

PART4 = """
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CHAPTER FIFTEEN: DEEP ARCHIVE — VOICES FROM PARLIAMENTARY DEBATES ON FOREIGN POLICY

15.1 Nehru's Philosophy of Non-Alignment: Extended Parliamentary Arguments

To understand India's foreign policy through the lens of parliamentary history, one must begin with the body of Nehruvian argument in its full richness, for it was Jawaharlal Nehru who established virtually every conceptual framework that subsequent governments either continued, modified, or argued against. The parliamentary archive of the 1950s is, in foreign policy terms, an extended seminar on the foundations of post-colonial international relations conducted by a man of unusual intellectual gifts before an audience of newly elected democratic representatives.

Nehru's understanding of non-alignment was not, as its critics sometimes caricatured it, simple neutralism or indifference to the global struggle between democracy and totalitarianism. In his parliamentary speeches he was at pains to clarify the distinction. Speaking in the Lok Sabha in December 1953, he said: "We are told we must choose a side, that the world is divided and we cannot stand apart from its divisions. I say this is precisely the illusion we must resist. The world is not divided between two camps and two camps only. It contains hundreds of millions of people who desire peace, who desire development, who desire to live without the constant fear of annihilation. These people — the majority of humanity — are not represented adequately in the councils of either great power. India's role is to represent them, to speak for them, to remind the powerful that the needs of the many are not served by the competition of the few."

This was not naivety. Nehru's parliamentary record shows a consistent understanding that power politics were real and that India had to engage with them. What he refused to accept was the binary framing that the Cold War offered: you were either with the West or against it. His parliamentary arguments for a "third way" — presented not as a geographical midpoint between two camps but as a principled rejection of military-bloc thinking — were sophisticated enough that even critics who disagreed with his conclusions found it difficult to characterise his position as simple-minded.

The most philosophically interesting of his parliamentary foreign policy speeches were those he delivered in response to what he called "the atom bomb mentality" — the growing assumption in both American and Soviet strategic thinking that nuclear weapons could be used in warfare and that their use was a legitimate extension of political will. Nehru's parliamentary denunciations of nuclear weapons — delivered with increasing urgency through the mid-1950s as both superpowers tested increasingly powerful devices — were the precursor to his 1956 call for a test moratorium and to India's long tradition of parliamentary support for nuclear disarmament.

In the Rajya Sabha on 19 November 1956, after both the United States and the Soviet Union had tested hydrogen bombs, Nehru delivered one of his most remarkable speeches: "We are told that these weapons give us security. I say they give us nothing of the kind. They give us the capacity for mutual destruction on a scale that no previous generation has had to contemplate. A world in which both sides possess the hydrogen bomb is not a safer world. It is a world in which the margin for error has been eliminated, in which a miscalculation by either side, a failure of nerve, a technical malfunction, could eliminate civilization as we know it. India refuses to accept that this is the highest form of security that human ingenuity can devise. We shall press, in every forum available to us, for the abolition of these weapons, not because we are innocent of the realities of power, but because we understand those realities better than those who believe that power resides ultimately in the capacity for destruction."

The parliamentary responses to such speeches were varied. Congress members applauded enthusiastically. Jan Sangh members asked pointed questions about whether India's refusal to build its own nuclear weapons left it vulnerable to the nuclear blackmail it was condemning in others — a question that Nehru could never fully answer. CPI members supported the disarmament argument while pressing for greater explicit alignment with the Soviet Union, which they characterised as more genuinely committed to disarmament than the United States. And the independent members and smaller parties expressed a range of positions from full agreement to scepticism about whether India's moral authority could be translated into any material international influence.

What Nehru's parliamentary speeches on disarmament established — and this is significant for understanding all subsequent nuclear debates in Parliament — was the concept that India's security interests and its moral commitments were not simply identical. When he spoke against nuclear weapons in Parliament, he was simultaneously maintaining India's option to develop them — the 1948 Atomic Energy Act had already set up the infrastructure — while arguing that the world needed to move in the opposite direction. This dual track — moral advocacy for disarmament, practical preparation for deterrence — was not hypocrisy in Nehru's mind. It was the management of an imperfect reality in the direction of a more perfect ideal. But it planted the seeds of every subsequent ambiguity in India's nuclear policy.

15.2 The Kashmir Permanence: A Longitudinal Reading of Parliamentary Debate

No issue has appeared in Indian parliamentary debates more continuously, more emotionally, and more inconclusively than Kashmir. A reading of parliamentary proceedings from 1952 to 2025 on the Kashmir question reveals both the remarkable continuity of India's formal position and the enormous practical changes in how that position has been defended, modified, and occasionally threatened.

In the early years — the First and Second Lok Sabhas, 1952 to 1962 — the Kashmir debate was shaped primarily by the UN Security Council resolutions of 1948 and 1949, which called for a plebiscite. Nehru's position in those debates was formally consistent with the plebiscite commitment while quietly moving away from it in practice. The parliamentary questions pressed him on specific: Would India accept a plebiscite in the current circumstances? What conditions would have to be met before a plebiscite could be held? Was there a timeline? His answers were always qualified — the plebiscite required Pakistani withdrawal first, and Pakistan had not withdrawn — but he never formally repudiated the commitment.

This formal position created systematic parliamentary difficulties. On one side, Jan Sangh members argued that India should simply declare Kashmir integrated and challenge the world to accept it, rather than maintaining the fiction that a plebiscite might someday be held. On the other side, the CPI argued that India's democratic legitimacy required it to honour its plebiscite commitment, that the failure to do so was weakening India's moral position internationally. Nehru navigated between these positions with characteristic skill — acknowledging the concerns of the first group by pointing to the security implications of Pakistani-occupied Kashmir, and responding to the second group by emphasising the conditions Pakistan needed to meet before a plebiscite was possible.

The 1957 elections to the Kashmir Constituent Assembly — which ratified accession to India — were presented to Parliament as a form of popular endorsement that effectively superseded the earlier plebiscite commitment. This argument was legally questionable and was not universally accepted internationally, but it provided the parliamentary template for India's subsequent Kashmir position: accession had been democratically ratified, the matter was constitutionally settled, and Pakistan's continuing claim was interference in India's internal affairs. This framing — which successive Indian governments have maintained in Parliament ever since — was established in parliamentary debate in 1957 and has remained the formal Indian position for nearly seventy years.

The Kashmir debates of the 1960s were shaped by the 1965 war and the Tashkent negotiations. The Tashkent Declaration's commitment to "return to positions held before 5 August 1965" — which implied a return to the status quo ante, including the LoC — was defended in Parliament as a temporary measure that did not prejudice India's final position on Kashmir. But members on all sides understood that the return of Haji Pir and other strategic passes had weakened India's negotiating position. The parliamentary debates of 1966 on Tashkent were the first occasion on which serious questions were asked about whether India's diplomatic settlements of military conflicts were systematically less favourable than India's military achievements might have warranted.

The Simla Agreement of 1972 — which converted the 1949 UN ceasefire line into the Line of Control and committed both sides to bilateral resolution of all disputes — was the most significant Kashmir-related parliamentary debate of the Indira Gandhi era. The government's parliamentary defence of Simla rested on two claims: first, that the LoC was now formally recognised as a de facto boundary, which strengthened India's position; second, that the commitment to bilateralism effectively excluded UN and other international mediation, removing the pressure of the 1948 resolutions. Both claims were true but incomplete: the LoC was not the international boundary, and the bilateral commitment was dependent on Pakistani good faith that was not always forthcoming.

The parliamentary debates on Kashmir in the 1990s — during the height of the insurgency in the Valley — were among the most painful of the post-independence period. The eruption of Kashmiri militancy in 1989, the mass displacement of Kashmiri Pandits in 1990, the human rights allegations against Indian security forces, and the Pakistani support for insurgent groups created a parliamentary debate that simultaneously had to address humanitarian concerns, security imperatives, political negotiations, and international pressure. Members from across the spectrum — Congress, BJP, Left, regional parties — brought strongly felt but often contradictory convictions to these debates, and the government's management of parliamentary opinion on Kashmir during this decade required constant attention and considerable skill.

The Vajpayee government's approach to Kashmir — combining military pressure with political outreach, leading to the Lahore Declaration and then the Agra Summit — generated parliamentary debates about whether political dialogue was compatible with ongoing cross-border terrorism. These debates were never fully resolved; the relationship between political engagement and security conditions was genuinely complex, and the parliamentary arguments reflected that complexity.

The abrogation of Article 370 on 5 August 2019 — under which the special constitutional status of Jammu and Kashmir was revoked and the state was reorganised into two Union Territories — was arguably the most significant single action taken by any government on the Kashmir question since the 1952 accession negotiations. The parliamentary debate on the reorganisation was conducted under conditions that were deeply controversial. Parliament was in session and voting on the legislation; but the Valley itself was under a communication and movement lockdown, Kashmiri political leaders were in detention, and the opposition members who might have opposed the legislation most strongly had been effectively silenced.

The Rajya Sabha debate on the Jammu and Kashmir Reorganisation Bill, 2019 was remarkable for its procedural drama — with the Home Minister Amit Shah introducing the bill under Article 370 itself, which allowed it to be passed by Parliament acting as the J&K Constituent Assembly — and for the quality of the opposition arguments, which focused less on the ultimate question of J&K's constitutional status (where the Congress had always been ambivalent) and more on the process: the lack of consultation, the use of President's Rule to allow Parliament to act as the state legislature, and the detention of elected politicians without charge.

The parliamentary debate after the Article 370 abrogation — in subsequent sessions — focused on the restoration of statehood (the Union Territory status was explicitly described by the government as temporary), on the economic consequences of the reorganisation, on the human rights situation in the Valley, and on the international reactions to the decision. These debates continued through 2020, 2021, 2022, and 2023, with the government maintaining that the reorganisation was permanent and constitutional while the opposition continued to challenge its legitimacy.

The Supreme Court's December 2023 judgment upholding the constitutionality of the Article 370 abrogation while directing elections in Jammu and Kashmir — and the subsequent Jammu and Kashmir assembly elections in October 2024, won by the National Conference — added new dimensions to the parliamentary debate. The return of elected government in the Union Territory created a new set of parliamentary questions: what was the relationship between the elected state government and the Union Territory administration, what were the conditions under which statehood would be restored, and how did the new political reality affect the broader Kashmir question.

The Kashmir parliamentary debates of 2025 represent the latest chapter in a seventy-three-year story that is still far from its end. The parliamentary record shows both the remarkable constancy of India's formal position — accession was legal, the territory is India's, Pakistan's claim is interference in internal affairs — and the enormous changes in the practical reality on the ground, from Nehru's tentative plebiscite commitment to the Article 370 abrogation and its aftermath.

15.3 The Pakistan Problem: Parliamentary Cycles of Engagement and Confrontation

If Kashmir is the permanent crisis in Indian parliamentary foreign policy debates, the broader relationship with Pakistan is the permanent problem — the question that has generated more sustained parliamentary attention than any other bilateral relationship and whose parliamentary history reveals, with unusual clarity, the limits of parliamentary influence over deeply entrenched security dilemmas.

The parliamentary history of India-Pakistan relations follows a recognisable cycle: diplomatic initiative, raised expectations, crisis or collapse, recrimination, and eventually a new initiative. This cycle has repeated itself at least six times across the seventy-three years covered by this study. Each iteration has been accompanied by parliamentary debates that are structurally similar: initial cautious enthusiasm for engagement, mounting scepticism as Pakistani actions contradict Pakistani words, sharp criticism when things go wrong, and calls for a fundamental reassessment of approach.

What is remarkable is how little these cycles have taught policy-makers about what is fundamentally possible in the India-Pakistan relationship. Each new government — of whatever party — has believed, at least initially, that it could break the cycle through some novel combination of political will, strategic creativity, and personal chemistry. And each has, eventually, discovered the limits imposed by the structural features of the relationship: Pakistan's military's dominance of its own foreign policy, the irredentist claims on Kashmir that no Pakistani government can formally abandon, the militant networks whose existence requires continued tension with India, and the domestic political costs on both sides of genuine compromise.

Parliament's role in this cycle has been primarily reactive: celebrating the initiatives, criticising the collapses, and occasionally asking whether the cycle itself should be broken by a fundamentally different approach. The Rajya Sabha has been particularly valuable in these meta-debates — the debates about whether engaging Pakistan was strategically sensible at all. The contributions of former officials and academics who sit in the Rajya Sabha by nomination have added depth to these discussions that would otherwise have been lacking.

The most significant parliamentary intervention in the Pakistan policy cycle came, arguably, not during any of the bilateral crises but in the sustained debates of the 2008–2012 period following the Mumbai attacks. The parliamentary pressure — sustained, cross-party, informed by public anger — created conditions in which the resumption of Composite Dialogue was genuinely difficult, forcing both the UPA government and subsequently the BJP government to develop alternative frameworks for managing the relationship without fully normalising it. The concept of "talks about talks" — preliminary discussions about whether conditions were right for substantive dialogue — is partly a product of the parliamentary pressure that made unconditional engagement with Pakistan politically impossible after 2008.

15.4 The Nuclear Debates: A Legislative History

The evolution of India's nuclear policy as reflected in parliamentary debates deserves extended treatment because it is one of the areas where Parliament's influence has been most direct and most consequential. The parliamentary history of India's nuclear policy is a sixty-year story of gradual democratisation of a decision that was, in its initial phases, made almost entirely within a small circle of scientists and political leaders without any real parliamentary engagement.

The Atomic Energy Act of 1948 — which created the Atomic Energy Commission and gave the Department of Atomic Energy exceptional authority and secrecy — was debated in the Constituent Assembly but not in ways that seriously engaged with the strategic implications of nuclear weapons development. Nehru presented the act primarily as a vehicle for the peaceful development of nuclear energy and explicitly discouraged speculation about weapons applications. This framing — which was sincere in terms of Nehru's immediate intentions but deeply ambiguous about long-term possibilities — established the pattern of parliamentary engagement with nuclear affairs that persisted for decades.

For the first fifteen years of Indian nuclear development, Parliament received very little information about the programme's actual content and direction. The Atomic Energy Commission's budget was presented to Parliament as a routine ministry expenditure; questions about its programmes received brief answers about peaceful applications; and the actual state of India's weapons-relevant research was simply not discussed in Parliament at all. The extraordinary secrecy provisions of the Atomic Energy Act effectively excluded Parliament from any meaningful oversight of the most consequential technology programme in Indian history.

This changed somewhat after the 1964 Chinese nuclear test, which forced a more open parliamentary debate about India's strategic options. But even then, the parliamentary debate was conducted without detailed technical information about what India was capable of or how rapidly it could develop a weapons capability. Members debated policy alternatives — weapons, peaceful applications, non-proliferation — without the technical knowledge to evaluate the feasibility of various options. The government's management of parliamentary debate on nuclear affairs was a masterclass in using formal transparency — providing answers to questions — to conceal substantive opacity about actual programmes and capabilities.

The 1974 test changed the character of parliamentary nuclear debate in ways that were significant but incomplete. The test's demonstration that India had achieved nuclear explosive capability — however the government characterised it — opened space for more frank discussion of India's strategic options. Members now knew that India could build nuclear weapons; the question was whether it should. This shifted the parliamentary debate from the abstract — should India develop nuclear weapons capability — to the concrete — having developed it, what should India do with it?

But the government's insistence on calling the 1974 test a "peaceful nuclear explosion" imposed continuing limitations on the parliamentary debate. Members who wanted to discuss India's weapons programme directly were told that there was no weapons programme. Members who wanted to discuss the strategic implications of the demonstrated capability were told that the capability was civilian in nature. The strategic ambiguity that the government maintained in its public diplomacy was reproduced in its parliamentary communications, and this ambiguity — useful diplomatically — was simultaneously a constraint on Parliamentary understanding of what was actually happening.

The most productive period of parliamentary nuclear debate was, paradoxically, the years after the 1998 tests — when the programme was no longer ambiguous and the government could engage with Parliament directly on nuclear strategy. The nuclear doctrine debates of 1998 and 1999, the discussions of no-first-use policy, the parliamentary committee investigations into command-and-control arrangements, and the extended debates about the nuclear deal — all of these were genuine parliamentary engagements with substantive nuclear policy questions. They represent the highest water-mark of parliamentary involvement in nuclear affairs and demonstrate what a genuine parliamentary debate on nuclear strategy looks like when the government is willing to provide real information and engage with real arguments.

15.5 The Economy and Foreign Policy: Parliament's Often-Ignored Contribution

The relationship between economic policy and foreign policy has been consistently undervalued in parliamentary discussions and in scholarly treatments of Indian foreign policy history. Yet some of the most consequential foreign policy decisions India has made — including the 1991 economic liberalisation, the decision to seek IMF assistance, the opening of the insurance and banking sectors to foreign investment, the semiconductor partnership with the United States — were made primarily in the domestic economic domain and only secondarily as foreign policy choices. Parliament's role in these decisions was primarily through its economic oversight functions rather than its foreign policy functions, but the consequences for India's international position were enormous.

The 1991 economic crisis — the balance-of-payments crisis that nearly drove India to default on its foreign debt — was discussed in Parliament primarily in terms of its domestic economic dimensions: the need to reduce the fiscal deficit, to liberalise import licensing, to privatise public enterprises. The foreign policy implications of the liberalisation — the transformation of India's economic relationship with the United States and the West, the opening to foreign investment that would over the following decades reshape India's relationship with global capital — were acknowledged in parliamentary debate only gradually.

The debates over foreign direct investment policy in the 1990s and 2000s were simultaneously economic and foreign policy debates: questions about how much foreign ownership of Indian companies was strategically acceptable, which sectors should remain protected from foreign competition, and what conditions should be attached to foreign investment were all questions with clear foreign policy dimensions. The parliamentary debates on these issues were often more focused on economic interests — the protection of domestic industries, the welfare of workers — than on strategic considerations. But they shaped the framework within which India's economic integration with the world proceeded, and they established the political limits within which foreign economic policy could be made.

15.6 South-South Solidarity: Parliament and the Global South Agenda

One dimension of India's foreign policy that has been consistently present in parliamentary debates but rarely analysed is India's engagement with the global South — the developing countries of Africa, Latin America, and Asia — as a defining element of its international identity. From Nehru's enthusiastic support for newly independent African nations to Modi's G20 championing of the African Union's membership, India's relationship with developing countries has been a consistent theme in parliamentary foreign policy discussions.

The Non-Aligned Movement — established at the Belgrade Summit of 1961, building on the Bandung Conference of 1955 — was one of the vehicles for India's South-South engagement, and its evolution was tracked carefully in Parliament. Parliamentary debates on NAM summits — from Belgrade through Lusaka (1970), Algiers (1973), Colombo (1976), Havana (1979), Delhi (1983), and subsequent summits — provide a running account of how India's position within the organisation evolved as its membership changed and as the Cold War context that had originally given NAM its purpose dissolved.

The 1983 Delhi NAM Summit — which India hosted and which elected Indira Gandhi as chairman — was presented to Parliament as a triumph of Indian diplomatic leadership. But the parliamentary debates around it revealed the declining relevance of NAM as a strategic vehicle: with 101 member states, many with very different and sometimes conflicting interests, the organisation's capacity to articulate a coherent policy position was severely limited. Parliamentary members from across the political spectrum questioned whether NAM was still serving Indian foreign policy interests or whether it had become a ritual whose diplomatic costs — in the form of commitments to positions that constrained India's relationships with the West — outweighed its benefits.

This questioning became more explicit in the 1990s, as NAM meetings continued with decreasing substance. By the Vajpayee period, India's participation in NAM was almost an afterthought in parliamentary foreign policy debates — mentioned in annual foreign policy statements, debated briefly in question hour exchanges, but no longer generating the sustained attention that the organisation had commanded in the 1960s and 1970s. The Modi government's decision to send lower-level representation to some NAM meetings — reflecting the reality that NAM had ceased to be a serious diplomatic vehicle — was barely registered in parliamentary debate.

The Indian Technical and Economic Cooperation programme — through which India provides development assistance, scholarships, and technical training to developing countries — has been the subject of consistent if not always intense parliamentary attention. The ITEC programme's parliamentary history reveals an interesting evolution: initially conceived as part of India's solidarity with the developing world and funded at very modest levels, it grew over the decades into a significant instrument of what is now called "development diplomacy," building goodwill and relationships in Africa, Southeast Asia, and Central Asia that had clear strategic value. Parliamentary debates on ITEC — usually in the context of the MEA budget — tracked this evolution and occasionally generated calls for more resources, more systematic evaluation, and a clearer strategic framework.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CHAPTER SIXTEEN: THE MIDDLE POWERS AND INDIA — PARLIAMENTARY DEBATES ON MULTILATERAL RELATIONSHIPS

16.1 The United Nations: From Temple to Tool

India's relationship with the United Nations — and parliamentary debates about that relationship — traces a fascinating arc from the passionate multilateralism of the early post-independence decades to the more pragmatic, interest-based engagement of the present. In the Nehruvian period, the UN was genuinely central to India's foreign policy vision: it was the institutional embodiment of the international community, the vehicle through which small and medium powers could influence great-power behaviour, and the forum in which India's moral authority could be converted into diplomatic influence.

Nehru's parliamentary speeches on the United Nations were among his most eloquent. He believed in the UN as a principle — the idea that the world's nations could manage their disagreements through institutional mechanisms rather than through power alone — and he communicated that belief with genuine passion. His reports to Parliament after returning from UN General Assembly sessions or after significant UN decisions were major parliamentary events: long, wide-ranging speeches that placed specific UN actions in the context of the larger project of building international order.

The parliamentary debates on specific UN votes — how India voted, why it voted that way, what the consequences were for India's relationships with the great powers — were among the most consistently interesting of the Nehruvian period. The debates on the Korean War, on the successive Middle East crises, on the Congo peacekeeping operation, on decolonisation resolutions — all were conducted with reference to India's UN position and all generated parliamentary examination of the principles that should guide India's multilateral diplomacy.

By the 1970s and 1980s, the parliamentary relationship with the UN had changed in character. The organisation had expanded enormously — from 51 founding members to more than 150 — and its General Assembly had become more a vehicle for Third World bloc voting than the deliberative body that Nehru had envisioned. India's voting record at the UN had become more predictable and more bloc-driven; parliamentary debates on UN affairs were correspondingly less interesting and more formulaic. The real foreign policy action had moved to bilateral relationships and regional organisations.

The question of India's permanent membership of the UN Security Council — which has been raised in Parliament intermittently since the early 1990s and persistently since the 2000s — is one of the areas where parliamentary debate has been most clearly ahead of diplomatic reality. Parliamentary members across parties have consistently argued that India's size, its democracy, its nuclear capability, and its growing economic weight make its absence from the P5 an anomaly that should be corrected. Successive governments have pursued Security Council reform with varying degrees of energy and have reported back to Parliament on the progress — or lack of it — of these efforts.

The G4 initiative — in which India, Brazil, Germany, and Japan collectively pursue Security Council permanent membership — has been a consistent subject of parliamentary attention. Parliamentary members have asked sharp questions about the G4's strategy, about Chinese and American positions on expansion, about what India is prepared to offer in exchange for support for its candidacy, and about whether the realistic prospect of expansion is sufficient to justify the diplomatic capital being spent on it. The government's responses have been consistently optimistic in tone while acknowledging the structural difficulties. As of 2025, Security Council reform remains unrealised, and the parliamentary debates continue.

16.2 BRICS, SCO, and the Architecture of Multipolarity

The emergence of new multilateral frameworks — particularly BRICS (Brazil, Russia, India, China, South Africa) and the Shanghai Cooperation Organisation — has generated significant parliamentary debates about the relationship between India's Western partnerships and its membership in frameworks that include China and Russia.

India joined the BRICS grouping formally in 2009, and parliamentary debates on BRICS have tracked the organisation's evolution from a financial concept (the "emerging markets" idea of Goldman Sachs analyst Jim O'Neill) to a geopolitical alternative to Western-led institutions. The parliamentary debates on BRICS have been characterised by two competing assessments: those who see BRICS as a valuable vehicle for coordinating the emerging economies' position in global economic governance; and those who question whether an organisation that includes China — India's principal strategic rival — can serve India's interests without being captured by Chinese priorities.

The SCO debates have been even more charged, because the organisation's membership includes Pakistan — which joined in 2017 — as well as China. Parliamentary questions about India's SCO participation have asked: How can India be in the same organisation as Pakistan while simultaneously characterising Pakistan as a state sponsor of terrorism? What intelligence-sharing obligations does SCO membership entail, and how are these managed given that China and Pakistan are both present? Is India's SCO membership an independent strategic choice or is it primarily defensive — aimed at preventing India's exclusion from an Asian security architecture dominated by China?

The government's answers to these questions have been consistently pragmatic: BRICS and SCO are venues for engagement, not alliance commitments; India can participate in multilateral forums with countries with which it has serious disputes; and the alternative — staying out — would be worse. These answers are fundamentally sound but leave important questions about India's strategic coherence in an era of competing multilateral architectures.

16.3 Climate Change and Foreign Policy: The Parliamentary Dimension

Climate change has emerged over the last two decades as a foreign policy issue of the first order, generating parliamentary debates that have bridged the domestic and international domains in unusual ways. India's position at international climate negotiations — from Kyoto (1997) through Copenhagen (2009), Paris (2015), and the subsequent COP meetings — has been a subject of sustained parliamentary attention, reflecting both the domestic salience of climate impacts and the diplomatic sensitivity of India's negotiating position.

The parliamentary debates on India's climate position have been structured around a tension that is both economic and ethical: India is one of the world's largest emitters of greenhouse gases in absolute terms, but its per-capita emissions remain a fraction of those of developed countries; it has the development imperatives of a country where hundreds of millions still lack access to adequate energy; and it faces some of the world's most severe climate vulnerability. Balancing these realities in international negotiations — arguing that India has a right to develop while also acknowledging its responsibility to the global commons — has required considerable parliamentary communication.

The parliamentary debates on the Paris Agreement in 2015 — India's Nationally Determined Contributions, the timeline for achieving net-zero emissions, the financing requirements — were among the more technically sophisticated climate discussions in any legislature. Members asked detailed questions about the cost of India's renewable energy programme, about the implications of specific emission reduction targets for India's growth projections, and about the relationship between climate finance commitments from developed countries and India's own commitments. These questions reflected a genuine engagement with the technical dimensions of climate policy that would have been impossible in earlier decades.

The Modi government's announcement at the 2021 Glasgow COP — of a 2070 net-zero target and a 500 GW renewable energy target by 2030 — was presented to Parliament as a responsible contribution to global climate action that was consistent with India's development imperatives. The parliamentary reception was broadly positive, though some members from industrial states pressed questions about the coal transition timeline and the economic impacts on workers in mining regions. These debates illustrated both the growing sophistication of parliamentary climate engagement and the continuing tension between India's global commitments and its domestic economic realities.

16.4 The Indian Diaspora: Parliament's Growing Foreign Policy Constituency

The Indian diaspora — approximately thirty million people of Indian origin living outside India, the largest diaspora of any country in the world — has become an increasingly important foreign policy constituency over the decades covered by this study. Parliamentary debates about the diaspora have evolved from the early concern with protecting the rights of indentured labourers and their descendants (particularly in Fiji, Malaysia, and parts of Africa) to the more complex contemporary discussions about leveraging the political and economic influence of non-resident Indians and persons of Indian origin in the United States, United Kingdom, Canada, Australia, and the Gulf states.

In the early parliamentary debates — 1950s through 1970s — the diaspora question was primarily humanitarian: how to ensure that Indian-origin communities in the Caribbean, in East Africa, in Malaysia, and in Fiji were protected against discrimination and violence. Nehru's parliamentary statements on the situation of Indian communities in Kenya, Uganda, and South Africa during the decolonisation period reflected both genuine humanitarian concern and the difficulty of India's position: as a newly independent country committed to the principle of non-interference in the internal affairs of other sovereign states, it was hard to press other governments too strongly on the treatment of Indian minorities without violating the Panchsheel principles it publicly championed.

The expulsion of Asians from Uganda by Idi Amin in 1972 — when approximately fifty thousand Uganda Asians of Indian origin were given ninety days to leave the country — produced one of the most significant diaspora debates in Indian parliamentary history. The combination of the humanitarian emergency, the specific responsibility that India felt for people of Indian origin, and the difficult relationship with Uganda and with other East African governments generated a parliamentary debate that was simultaneously principled and practically constrained. India could not prevent the expulsion; it could offer some of those expelled the option of Indian citizenship; and it had to do so while maintaining working relationships with African governments whose support it needed in international forums.

The contemporary diaspora parliamentary debates are quite different in character. The political influence of Indian-Americans in the United States, of Punjabi-Canadians in Canada, of Gujarati-British in the United Kingdom, and of Keralite workers in the Gulf states is now a regular subject of parliamentary discussion. Members from states with large diaspora communities — Kerala, Punjab, Gujarat, Andhra Pradesh — regularly raise diaspora-related issues in Parliament: the welfare of workers in Gulf states, the political representation of diaspora communities in their countries of residence, the diaspora remittances that are a crucial source of foreign exchange for India, and the potential for diaspora political influence to shape host-country policies toward India.

The Modi government's systematic cultivation of the diaspora — through the Pravasi Bharatiya Divas convention, through events at Madison Square Garden and Wembley, through the "Howdy Modi" rally in Houston and the "Namaste Trump" event in Ahmedabad — was presented to Parliament as a new model of diaspora engagement: using the diaspora as an instrument of public diplomacy to build support for India in host-country politics. Parliamentary debates on this approach were generally supportive, with some members questioning the line between diaspora engagement and the appropriateness of India's government seeking to influence the domestic politics of other countries through the diaspora.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CHAPTER SEVENTEEN: FOREIGN POLICY AND DOMESTIC POLITICS — THE PARLIAMENTARY INTERFACE

17.1 Elections, Governments, and the Temptation of Foreign Policy

The relationship between domestic electoral politics and foreign policy has been a consistent source of distortion in Indian parliamentary foreign policy debates. Governments have been tempted to make foreign policy moves — visits, declarations, military actions — timed to maximise domestic political benefit rather than diplomatic effectiveness. Opposition parties have been tempted to criticise foreign policy decisions primarily for partisan reasons rather than for their strategic merits. And Parliament has sometimes been the arena in which these political games are played out, rather than a space for genuine policy deliberation.

The most systematic attempt to exploit foreign policy for electoral benefit occurred in the months leading up to the 2019 general elections. The Pulwama attack of February 2019 and the Balakot airstrikes that followed were both genuine events — the attack was a real terrorist atrocity, and the airstrikes represented a real military action — but their political management was visibly calibrated for maximum electoral impact. The timing, the messaging, the celebratory tone of government communications, and the parliamentary debate that accompanied these events were all shaped by the awareness that elections were just weeks away.

Parliamentary members across parties — including some from within the BJP's coalition partners — raised questions about whether the intelligence failure that allowed the Pulwama attack should be investigated and whether appropriate accountability measures had been taken. These questions received minimal engagement from the government. The political atmosphere of pre-election crisis nationalism made substantive accountability impractical, and the parliamentary debates of February-March 2019 on Pakistan and counter-terrorism were among the most politically charged and intellectually least productive of the Modi era.

The 2002 Gujarat riots — which occurred against the backdrop of India-Pakistan tensions and Operation Parakram — created a different kind of politicisation of foreign policy in Parliament. The communal violence, in which more than a thousand Muslims were killed, had significant foreign policy consequences: it damaged India's international reputation, complicated the government's efforts to maintain the moral high ground in its argument with Pakistan over terrorism, and provided opposition members with a powerful argument about the inconsistency between India's claimed democratic values and the reality of communal violence under BJP governance. The parliamentary debates of 2002 on both the Gujarat riots and the Pakistan situation were entangled with each other in ways that neither the government nor the opposition could fully manage.

17.2 Coalition Politics and Foreign Policy Constraints

The coalition era of Indian politics — from 1989 to 2014, with a brief interruption when the Congress achieved a majority in 1984 — created systematic constraints on foreign policy that were consistently reflected in parliamentary debates. Coalition governments must balance the foreign policy preferences of their component parties, and when those preferences diverge significantly — as they did on the Indo-US nuclear deal — the result is either prolonged paralysis or the kind of constitutional crisis that nearly ended the Manmohan Singh government in 2008.

The Left parties' foreign policy preferences — broadly anti-American, sympathetic to China and Russia, opposed to military alliances, sceptical of economic globalisation — were consistently the most difficult for Congress-led coalition governments to accommodate. From the 2004 formation of the UPA government to the 2008 confidence vote, the Left's parliamentary positions on foreign policy created constant friction with the government's strategic directions. The nuclear deal crisis was the most dramatic expression of this friction, but it was accompanied by equally difficult parliamentary debates on the India-Iran relationship (the Left wanted India to vote against the IAEA referral of Iran's nuclear programme, while the government felt it had to abstain), on the India-Israel defence relationship (the Left opposed any deepening of ties with Israel), and on the US military exercises with India (the Left opposed them as implying strategic alignment).

The BJP-led National Democratic Alliance governments of 1998–2004 faced different but equally real coalition constraints. The nuclear tests of 1998 were broadly popular across the NDA coalition, but the subsequent diplomatic management — including India's openness to a partial CTBT commitment and the Agra Summit's readiness to acknowledge Kashmir as a "core issue" — generated parliamentary tensions with the more hard-line elements of the coalition. Vajpayee's foreign policy was consistently more moderate and more diplomatically agile than the party positions of some of his coalition partners, and his parliamentary management of these tensions was a consistent test of political skill.

The Modi government's single-party majority from 2014 to 2024 — and its comfortable majority even after 2024 — largely freed it from coalition constraints on foreign policy. But it created a different parliamentary dynamic: with no coalition partners to negotiate with and a very large majority in Parliament, the government was less constrained and less accountable, and the opposition's capacity to force policy changes through parliamentary mechanisms was correspondingly reduced. The combination of a strong executive majority and a weakened opposition contributed to the reduced quality of parliamentary foreign policy debate in the later years of the Modi era.

17.3 Regional Parties and Foreign Policy: The Tamil Nadu Case

Regional parties have occasionally had significant influence on foreign policy through their parliamentary positions, and no regional party's influence has been more consistent or more consequential than that of the Tamil Nadu parties — primarily the DMK and the AIADMK — on India's Sri Lanka policy. The Tamil connection — the cultural and linguistic affinity between Tamil Nadu and Sri Lankan Tamils — has made Sri Lanka policy unusually susceptible to regional parliamentary pressure in a way that has sometimes pulled Indian policy in directions that central strategic logic would not have chosen.

The IPKF deployment of 1987 was partly a product of Tamil Nadu political pressure on the Rajiv Gandhi government. The pressure from Tamil Nadu parties in Parliament — representing constituencies with strong emotional identification with the Sri Lankan Tamil cause — created political conditions in which India's intervention was seen as a response to genuine democratic demand rather than simply executive decision. This gave the intervention democratic legitimacy but also created the political constraints that made it difficult to adjust course as the operation went badly wrong.

The subsequent decisions on Sri Lanka — the withdrawal of the IPKF in 1990, the decision not to intervene in the final military campaign against the LTTE in 2009, the abstention on the UNHRC resolutions on Sri Lanka — were all made with one eye on Tamil Nadu parliamentary opinion. The UPA government's position on the 2009 UNHRC resolution — India abstained rather than voting against — was a compromise that satisfied almost no one: it was too soft for the international human rights community and too hard for the Tamil Nadu parties. The parliamentary debates on this decision illustrated the complexity of managing regional identity politics in the conduct of national foreign policy.

17.4 Parliament, Intelligence, and the Accountability Deficit

The relationship between parliamentary oversight and intelligence functions is one of the most persistent and least resolved problems in Indian democratic governance. India does not have a parliamentary committee with oversight of the intelligence services equivalent to the US Senate Intelligence Committee or the UK Intelligence and Security Committee. The Intelligence Bureau and the Research and Analysis Wing operate under very limited formal parliamentary accountability, reporting primarily to the Prime Minister's Office and providing only the most sanitised information to parliamentary committees.

This accountability deficit has had real consequences for Indian foreign policy. The intelligence failures that preceded the 1962 China war, the Kargil intrusion of 1999, the Mumbai attacks of 2008, and the Galwan crisis of 2020 were all cases where Parliament was either not informed in advance of the threat or not provided with accurate information in the immediate aftermath. In each case, parliamentary pressure eventually forced some accounting — the Henderson Brooks Report on 1962, the Kargil Review Committee, the parliamentary committees on counter-terrorism after Mumbai — but the accounting was always incomplete and always delayed.

The argument for limited parliamentary oversight of intelligence is straightforward: intelligence sources and methods must be protected, and parliamentary disclosure creates unacceptable risks of compromise. This argument is sound as far as it goes. But it does not justify the total absence of any parliamentary oversight mechanism. The alternative — a small, security-cleared parliamentary committee with oversight of intelligence organisation structures, budgets, and broad strategic directions, without access to source-specific operational intelligence — is available to India and has been recommended by multiple committees and commissions. Its persistent absence reflects both executive reluctance to accept any limitation on intelligence control and Parliament's own limited interest in institutionalising oversight of functions whose political sensitivity makes them uncomfortable to engage with.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CHAPTER EIGHTEEN: THE LANGUAGE OF FOREIGN POLICY IN PARLIAMENT — A LINGUISTIC ANALYSIS

18.1 From "World Peace" to "Strategic Autonomy": The Evolution of Parliamentary Foreign Policy Vocabulary

One of the most revealing ways to trace India's foreign policy evolution is through the evolution of the language used in parliamentary debates about international affairs. The vocabulary of foreign policy is not merely descriptive; it is constitutive — the words chosen to describe India's international position both reflect and shape the understanding of what that position is and should be.

The vocabulary of the Nehruvian period was moral and philosophical. Terms like "world peace," "collective security," "peaceful coexistence," "the international community," and "the rule of law among nations" were not rhetorical flourishes but the genuine conceptual framework within which Nehru and his parliamentary interlocutors understood India's role in the world. This vocabulary assumed that international relations could and should be governed by principles rather than power, that India's influence derived from the quality of its ideas rather than the size of its military, and that the most effective foreign policy was one that combined moral clarity with diplomatic flexibility.

The vocabulary began to change after 1962. "Security," "deterrence," "national interest," and "power balance" entered parliamentary discourse with increasing frequency. The shift was not sudden — Nehru himself had always acknowledged the reality of power politics, even if he preferred the language of principles — but it was systematic. By the Indira Gandhi period, parliamentary foreign policy debates used the vocabulary of realpolitik as naturally as the vocabulary of principled idealism, and the two vocabularies coexisted in a productive if sometimes contradictory tension.

The Vajpayee period introduced a third vocabulary layer: the technical language of nuclear strategy. "Minimum credible deterrence," "no first use," "second strike capability," "civilian command and control," "nuclear threshold" — these terms, which might have seemed arcane in parliamentary debate in 1960, were used with genuine precision in the Rajya Sabha debates of 1998 and 1999. This technical vocabulary reflected the growing sophistication of India's strategic community and its increasing willingness to engage directly with the strategic community's conceptual frameworks.

The Modi era has added yet another layer: the language of civilisational assertion. "Vishwaguru," "Vishwabandhu," "cultural connectivity," "people-to-people ties," "shared heritage," "ancient wisdom" — these terms, which draw on the Hindu nationalist tradition's understanding of India as a civilisation rather than merely a state, have given parliamentary foreign policy debate a cultural dimension that was largely absent from previous periods. The language of India as a great civilisation resuming its rightful place in the world — as distinct from the language of India as a developing country seeking strategic space — has reshaped how Parliament talks about India's international aspirations.

This linguistic evolution is not merely semantic. The choice of vocabulary in parliamentary foreign policy debate signals which values are being prioritised, which constituencies are being addressed, and which understanding of India's international identity is being promoted. The shift from "world peace" to "strategic autonomy" to "civilisational power" represents not just a change in rhetorical fashion but a genuine evolution in how India's Parliament understands what India is and what it is trying to be in the world.

18.2 Parliamentary Metaphors and Their Strategic Implications

Metaphors are particularly important in parliamentary foreign policy communication because they create mental frameworks within which specific decisions are understood. Several metaphors have been especially influential in Indian parliamentary foreign policy debate.

The "bridge" metaphor — India as a bridge between different worlds, different blocs, different civilisations — was central to the Nehruvian vision of non-alignment. India as a bridge between East and West, between the developed and the developing world, between communist and capitalist economic models — this metaphor positioned India as a unique intermediary whose value lay in its capacity to connect rather than to choose. Acharya Kripalani's 1959 parliamentary critique — "a bridge is useful only when it connects two banks; if one bank has been washed away, the bridge serves no purpose" — was devastating precisely because it undermined the metaphor's premises.

The "neighbourhood" metaphor — India as the largest member of a South Asian neighbourhood — shaped parliamentary debates on regional policy from the Gujral Doctrine through the Modi government's Neighbourhood First policy. But the metaphor concealed as much as it revealed: neighbourhoods have norms and obligations that are not always present in South Asian geopolitics, and the idea that India could be a "good neighbour" in the conventional sense was strained by the reality of deep-seated conflicts with Pakistan and significant power asymmetries with other neighbours.

The "swing state" metaphor — India as a country that could swing between competing great powers, extracting concessions from both in exchange for its alignment — became increasingly popular in parliamentary debates from the 2000s onward, as India's growing strategic weight gave it genuine leverage with multiple powers simultaneously. This metaphor was more realistic than the bridge metaphor — it acknowledged India's interest-based approach rather than pretending to pure principled neutrality — but it raised uncomfortable questions about whether perpetual oscillation between great powers was a sustainable strategic posture or whether it would eventually force India to make choices it had been avoiding.

The "Vishwaguru" metaphor — India as the world's teacher — is the most ambitious and the most contested of the contemporary parliamentary foreign policy metaphors. It positions India as the source of wisdom that a troubled world needs, drawing on ancient philosophical traditions of dharma, ahimsa, and universal brotherhood. Its appeal in parliamentary debate — and in the broader political culture — is genuine: it connects India's foreign policy aspirations to a deep civilisational pride that transcends party politics. Its limitations are also real: the world does not obviously need or want a teacher, and the gap between the aspiration and the reality of India's domestic governance is sometimes difficult to ignore.

18.3 Parliamentary Silences: What Is Not Said

A complete reading of parliamentary foreign policy debates must account for silences — the topics that are not discussed, the questions that are not asked, the alternatives that are not considered. These silences are often as revealing as the speeches.

The silence about Bangladesh in the 1972-1975 period — after the euphoria of the liberation war — is one of the most striking. Following the withdrawal of Indian troops in 1972, Parliament largely stopped discussing Bangladesh's political situation, even as Sheikh Mujibur Rahman's government degenerated into authoritarianism and eventually succumbed to a military coup in August 1975 that killed Mujibur Rahman and most of his family. India's response to the coup — essentially acceptance of the new military government with relatively little parliamentary debate — contrasted sharply with the passionate parliamentary identification with Bangladesh's democratic aspirations in 1971. The silence about Bangladesh's democratic reversal was, in its way, an acknowledgment that India's intervention had been primarily strategic rather than purely democratic.

The silence about Tibet since the early 1960s is another significant parliamentary omission. After the initial debates on the Dalai Lama's asylum and the 1962 war's connection to the Tibet question, Parliament largely ceased to discuss Tibet's political status in any serious way. Chinese sovereignty over Tibet — however contested its legal and moral foundation — became a parliamentary given, and members who raised questions about Tibetan autonomy or the treatment of Tibetans were typically told that the question was a matter of China's internal affairs. This silence has been maintained with remarkable consistency across governments of very different political complexions.

The silence about India's covert operations — in Pakistan, in Nepal, in Sri Lanka, and elsewhere — is structurally determined by the secrecy of intelligence activities but has sometimes concealed actions that might have generated significant parliamentary debate had they been known. The allegations, never fully addressed in Parliament, about Indian intelligence involvement in various regional political developments — the political dynamics in Nepal, the management of factions in Sri Lanka, the support or non-support for various Pakistani political actors — have occasionally surfaced in parliamentary questions but have never been systematically addressed.

The silence about India's arms export programme has been a more recent and more contested omission. India has become a growing arms exporter — selling military equipment to countries in the Middle East, Southeast Asia, and Africa — but parliamentary debates on the ethical and strategic dimensions of India's arms exports have been limited. Questions about whether India's arms exports to specific countries are consistent with India's stated commitment to non-interference and peaceful coexistence have been raised occasionally, but without the sustained engagement that the size and growth of the arms export programme would seem to warrant.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CHAPTER NINETEEN: THE FUTURE OF PARLIAMENTARY FOREIGN POLICY OVERSIGHT — RECOMMENDATIONS AND PROSPECTS

19.1 The Case for Parliamentary Reform

The analysis in this study suggests that Parliament's contribution to Indian foreign policy has been significant but systematically constrained by institutional, informational, and political limitations. If India's Parliament is to play a more effective role in the conduct of foreign policy over the coming decades — as the country's international role expands and the decisions it must make become more consequential — several institutional reforms would significantly improve its capacity.

The most important reform is the establishment of a properly resourced and security-cleared Parliamentary Intelligence and Security Committee. Such a committee — modelled on the UK's Intelligence and Security Committee or the US Senate Select Committee on Intelligence — would have access to classified assessments from the Intelligence Bureau, the Research and Analysis Wing, and the Defence Intelligence Agency. Its proceedings would be confidential, but it would publish reports on broad intelligence community capabilities and performance, on major intelligence failures, and on the alignment of intelligence resources with national strategic priorities. This committee would not make intelligence decisions; that remains an executive function. But it would provide the parliamentary accountability that is currently entirely absent.

The second reform is the strengthening of the Standing Committee on External Affairs, including increased budget for independent research, expanded access to diplomatic dispatches and treaty texts, and a mandatory government response to all committee reports within ninety days. The current committee is valuable but under-resourced; it often lacks the research capacity to independently evaluate government claims and is dependent on the ministry's own analysis for much of its information. A more independent committee would improve the quality of parliamentary scrutiny without compromising executive flexibility.

The third reform is the extension of the parliamentary calendar. India's Parliament currently sits for fewer days per year than almost any comparable democracy — typically 60 to 70 days, compared to 140 to 150 for the UK House of Commons or 180 for the US Congress. The shortage of parliamentary time is a structural constraint on the quality of all parliamentary business, including foreign policy debates. There is no practical reason why India's Parliament cannot sit for significantly more days per year, and the improvement in the quality of parliamentary work — including foreign policy oversight — would be substantial.

The fourth reform is the development of parliamentary expertise. Most MPs have limited background in foreign affairs, and the parliamentary support services available to them — research staff, analytical resources, briefing papers — are inadequate for the complexity of the foreign policy questions they are asked to address. The expansion of parliamentary research services, the creation of subject-matter expert pools available to committee chairs, and the development of training programmes for MPs on specific foreign policy areas would all contribute to improved parliamentary engagement with international affairs.

19.2 The Prospects for Enhanced Parliamentary Role

The prospects for enhanced parliamentary engagement with foreign policy are affected by trends in both the international environment and India's domestic political system. On the international side, the growing complexity of the challenges India faces — climate change, cyber security, AI governance, supply chain security, great-power competition — will increase the demand for informed parliamentary engagement. Problems that were once relatively simple questions of bilateral diplomacy are now multidimensional challenges requiring engagement across departments and across sectors. Parliamentary capacity to engage with this complexity has been increasing, but it needs to increase faster than the complexity of the challenges.

On the domestic political side, the trends are more mixed. The growing majoritarian tendency in Indian politics — the weakening of coalition incentives, the growing dominance of the executive over the legislature, the declining independence of parliamentary institutions — poses real risks to the quality of parliamentary foreign policy oversight. A Parliament that is fully captured by the executive — that provides endorsement rather than scrutiny, that celebrates rather than challenges — would be a significant democratic loss, and not only for foreign policy.

At the same time, the digitisation of parliamentary proceedings, the growing civil society engagement with foreign policy issues, the rise of think tanks and academic expertise that MPs can draw on, and the increasing education and sophistication of MPs themselves — all of these are positive trends that partially offset the majoritarian drift. India's democracy remains robust enough that Parliament retains the capacity to be a genuine accountability mechanism, even if it does not always fulfil that capacity.

19.3 India's Parliament in the Global Context

India's Parliament's engagement with foreign policy is, finally, best understood in comparative context. How does India compare with other democracies in the parliamentary scrutiny of foreign policy? The comparison is not always flattering to India, but it is not uniformly negative either.

On the positive side, India's Parliament has a long tradition of substantive foreign policy debate that many developing-country legislatures lack. The quality of Question Hour on foreign affairs is generally high. The standing committee system, while under-resourced, is functional and produces genuinely valuable work. And the constitutional architecture — which makes the government responsible to Parliament and requires it to maintain parliamentary confidence — provides a fundamental accountability mechanism that purely presidential systems lack.

On the negative side, India lacks the treaty ratification power of the US Senate, which is the most powerful single mechanism of parliamentary foreign policy oversight in any democracy. It lacks the security committee oversight structure that has become standard in NATO member states. It lacks the parliamentary commissioner or independent oversight institutions that some democracies use to supplement formal committee work. And it has, in recent years, sat for fewer days and debated foreign policy for fewer hours than would be desirable given the complexity of India's international situation.

The picture is mixed but not discouraging. India's Parliament is not a foreign policy parliament in the sense that the US Senate is; it does not have the formal powers or the institutional resources to be so. But it is not irrelevant — it has shaped major decisions, forced important accountabilities, and occasionally prevented significant errors. The question for the future is whether it can develop the institutional capacity to be more systematically effective: to provide continuous rather than episodic oversight, to engage with the full complexity of twenty-first-century foreign policy, and to hold successive governments accountable not just for their major decisions but for the daily conduct of India's relationships with the world.

That is an ambitious agenda. But India's Parliament has shown, across seventy-three years, that it is capable of ambition — and of the occasional parliamentary moment that rises to meet the historical occasion.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EPILOGUE: PARLIAMENT SPEAKS — SELECTED PASSAGES FROM THE DEBATES

The richness of India's parliamentary foreign policy record can be suggested by a selection of characteristic passages from across the seventy-three-year period covered by this study. These passages — drawn from the official debates of the Lok Sabha and Rajya Sabha — give a sense of the range and quality of parliamentary foreign policy discourse.

JAWAHARLAL NEHRU, Lok Sabha, December 1952:
"We are asked which side we are on. We are on the side of peace. We are on the side of Asia's and Africa's peoples who are asserting their right to self-determination. We are on the side of those who suffer and those who seek justice. We are not on the side of any military bloc, because we believe that military blocs do not bring peace — they bring the very conflict they profess to prevent. India will not be an instrument of any power's policy. India will be an instrument of India's policy, and India's policy is the creation of a world in which war is impossible."

ACHARYA J.B. KRIPALANI, Rajya Sabha, October 1959:
"The Prime Minister tells us that we must maintain friendship with China because we cannot change geography. I agree we cannot change geography. But geography does not require us to be blind. Geography does not require us to overlook the systematic occupation of our territory. Geography does not require us to pretend that a state which has swallowed Tibet whole will be satisfied with nothing further. If Hindi-Chini bhai-bhai means anything, it must mean that a brother who takes your territory and then invites you to dinner is a brother whose invitations should be examined with some care."

JAWAHARLAL NEHRU, Lok Sabha, November 1962:
"We misjudged. That is the plain truth of it. We believed that friendship could prevail over interest. We believed that the stated commitments of a government reflected its actual intentions. We were wrong. The lesson I draw from this — and I draw it with great pain, for these were genuine beliefs, not convenient fictions — is not that we should join the arms race, not that we should abandon our principles, but that we should hold our principles with open eyes. Peace is still the goal. Non-alignment is still the method. But they must be pursued with a clearer understanding of the environment in which we operate."

ATAL BIHARI VAJPAYEE, Lok Sabha, November 1971:
"What is happening in Bangladesh is not merely a political conflict between East and West Pakistan. It is a genocide. The word must be used plainly, because the evasion of plain words makes possible the evasion of plain duties. Hundreds of thousands of people have been killed — slaughtered — because of their ethnicity and their religion. Ten million refugees have crossed into India. The Prime Minister must tell this House what India intends to do. History will not forgive us if we stand by and watch. It will not forgive us if we take refuge in the conventions of non-interference while those conventions are being used to justify mass murder."

INDIRA GANDHI, Lok Sabha, December 16, 1971:
"Dacca is now the free capital of a free country. I congratulate the people of Bangladesh and the soldiers of all three services who made this possible. I want to say something to those who counselled us against this course — who told us that the world would not understand, that the great powers would punish us, that India had overreached. The world understands justice. The world recognises courage. And the people of Bangladesh will remember who stood with them when they needed help most."

A.K. GOPALAN, Rajya Sabha, 1974 [on the nuclear test]:
"We have proved that we can do what the great powers can do. For this we should be proud. But I want to ask the government: having proved it, what will we do with it? Will we use it for peace or for war? Will we use it to join the nuclear club and its perpetual arms race, or will we use it to prove that a country can have the capability and choose not to exercise it in the direction of weapons? The government owes Parliament a clear answer to this question. A 'peaceful nuclear explosion' that no one can define and everyone understands is not an answer."

VAJPAYEE, Lok Sabha, May 1998:
"India is now a nuclear weapons state. This is not a boast. It is a statement of fact, and it carries with it responsibilities that we accept fully. We have said — and we repeat it today — that we will not be the first to use these weapons. We seek no arms race. We threaten no country. But we reserve the right to defend ourselves, and we will do so with whatever means are necessary. To those who ask why we tested: because we had to ensure that what we possess is credible. Deterrence without credibility is not deterrence; it is hope. We prefer the certainty of deterrence to the uncertainty of hope."

MANMOHAN SINGH, Rajya Sabha, August 2006:
"The nuclear deal is not a compromise of India's sovereignty. It is the exercise of India's sovereignty. We have chosen, as a sovereign nation, to separate our civil from our military nuclear programme. We have chosen to accept safeguards on our civil facilities in exchange for access to fuel and technology that will power our development. We have not given up a single weapon. We have not signed the Non-Proliferation Treaty. We have not accepted any constraint on our strategic programme. What we have done is take India from the margin of the nuclear order to its mainstream. That is not weakness. That is wisdom."

SUSHMA SWARAJ, Rajya Sabha, August 2017 [on Doklam]:
"India's position is clear and consistent. Our troops are where they are because Chinese road-building in Doklam — territory which Bhutan considers its own and which India is committed to protect under the 2007 Treaty of Friendship — threatens India's security and Bhutan's sovereignty. We will not move until the situation is resolved through dialogue. We have been in communication with the Chinese side at multiple levels. We believe the situation can be resolved peacefully. We are patient. We are firm. And we expect the same patience and firmness from this House."

S. JAISHANKAR, Rajya Sabha, September 2020 [on Galwan]:
"Twenty of our soldiers died in the Galwan Valley on the night of 15 June 2020. They died defending Indian territory. I want to say this directly, because there have been questions about whether the government has been forthcoming. They died. China bears responsibility for what happened. The situation on the ground changed on the night of 15 June in ways that are unacceptable to India. We are engaged in military and diplomatic talks to resolve the situation. But let me be clear about what kind of resolution India will accept: one that restores the conditions that prevailed before April 2020. Not partial restoration. Full restoration. India does not accept changes to the status quo by force."

RAHUL GANDHI, Lok Sabha, 2020 [on Galwan, in opposition]:
"The government has been telling this House since June that there was no intrusion. Now we know there was. We know that Chinese troops occupied Indian territory. We know that twenty soldiers died. The government's obligation to Parliament is to tell the truth. When that obligation is not fulfilled, when Parliament is misled — even through omission, even through silence — it is not just a political embarrassment. It is a constitutional failure. The people of India deserve better from their elected government. They deserve a government that trusts Parliament enough to tell it what is happening on India's borders."

These passages — from the debates of the Lok Sabha and the Rajya Sabha across seven decades — illustrate the range and depth of parliamentary engagement with India's foreign policy. They show a Parliament that has been, at its best, genuinely deliberative: willing to ask hard questions, capable of eloquent advocacy, and able to provide the kind of democratic accountability that distinguishes India's foreign policy from that of non-democratic states.

They also illustrate the limits: the evasions, the partial truths, the silences behind the eloquence. No parliamentary system is free from these defects; India's is not unusual in its imperfections. But its record — preserved in the official debates that this study has drawn on — is a record that, on balance, serves the ideal of democratic self-governance as it applies to the most consequential decisions a country makes: the decisions about how it will engage with the world.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

print(f"Part 4 word count: {len(PART4.split())}")
